service: ses-lambda # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-email
  region: ap-south-1
  stage: prod


functions:
  mailer:
    handler: handler.mailer
    events:
      - http:
          path: /mail
          method: post
          cors: true

    environment:
      SENDER_EMAIL: admin@neemtreeagrico.in

